### ISSUE TITLE
Can't use after last update

### ISSUE THREAD

**Issue by Grimmoire** [RoxasShadow/Dumper#2]
The JSON gem is installed so I don't know what's wrong
```
$ dumper
/home/grimm/.gem/ruby/2.1.0/gems/json-0.4.3/lib/json.rb:161:in `rescue in <module:JSON>': uninitialized constant JSON::Iconv (NameError)
	from /home/grimm/.gem/ruby/2.1.0/gems/json-0.4.3/lib/json.rb:155:in `<module:JSON>'
	from /home/grimm/.gem/ruby/2.1.0/gems/json-0.4.3/lib/json.rb:122:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/grimm/.gem/ruby/2.1.0/gems/image-dumper-0.7.5/lib/dumper.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/grimm/.gem/ruby/2.1.0/gems/image-dumper-0.7.5/bin/dumper:20:in `<top (required)>'
	from /home/grimm/.gem/ruby/2.1.0/bin/dumper:23:in `load'
	from /home/grimm/.gem/ruby/2.1.0/bin/dumper:23:in `<main>'
```

**Comment by Grimmoire** [comment]
is this project dead?

**Comment by RoxasShadow** [comment]
Nope, I just need some time to allocate in this project.

**Comment by RoxasShadow** [comment]
c95e2a6..0d877b6

Fakku is now working fine. For boorus like safebooru, it is unable to associate to the right profile without you, so please help it by using `--profile booru`. Now `dumper` alerts you about this, anyway.

**Comment by pdostal** [comment]
Nice :+1: Thanks
